export const DAYS_REQUEST = "DAYS_REQUEST";
export const DAYS_SUCCESS = "DAYS_SUCCESS";
export const DAYS_FAILURE = "DAYS_FAILURE";

export const ADD_EXERCISE_REQUEST = "ADD_EXERCISE_REQUEST";
export const ADD_EXERCISE_SUCCESS = "ADD_EXERCISE_SUCCESS";
export const ADD_EXERCISE_FAILURE = "ADD_EXERCISE_FAILURE";

export const EDIT_EXERCISE_REQUEST = "EDIT_EXERCISE_REQUEST";
export const EDIT_EXERCISE_SUCCESS = "EDIT_EXERCISE_SUCCESS";
export const EDIT_EXERCISE_FAILURE = "EDIT_EXERCISE_FAILURE";